# File automatically generated by build.rs.
# Changes made to this file will not be saved.
from typing import List, Tuple, Any, Optional, Union, ClassVar


def read_adj(path: str) -> AdjData: ...


class AdjData:
    entries: list[AdjEntryData]

    def __init__(self,) -> None: ...
    
    def save(self, path: str) -> None: ...


class AdjEntryData:
    mesh_object_index: int
    vertex_adjacency: list[int]

    def __init__(
        self,
        mesh_object_index: int
    ) -> None: ...
    
    @staticmethod
    def from_mesh_object(mesh_object_index: int,
                         mesh_object: MeshObjectData) -> AdjEntryData: ...
