# File automatically generated by build.rs.
# Changes made to this file will not be saved.
from typing import List, Tuple, Any, Optional, Union, ClassVar


def read_meshex(path: str) -> MeshExData: ...


class MeshExData:
    mesh_object_groups: list[MeshObjectGroupData]

    def __init__(self) -> None: ...

    @staticmethod
    def from_mesh_objects(objects: list[MeshObjectData]) -> MeshExData: ...
    
    def save(self, path: str) -> None: ...


class MeshObjectGroupData:
    bounding_sphere: list[float]
    mesh_object_name: str
    mesh_object_full_name: str
    entry_flags: list[MeshObjectGroupData]

    def __init__(
        self,
        bounding_sphere: list[float],
        mesh_object_name: str,
        mesh_object_full_name: str,
        entry_flags: list[MeshObjectGroupData]
    ) -> None: ...


class EntryFlags:
    draw_model: bool
    cast_shadow: bool

    def __init__(
        self,
        draw_model: bool,
        cast_shadow: bool
    ) -> None: ...
