# File automatically generated by build.rs.
# Changes made to this file will not be saved.
from typing import List, Tuple, Any, Optional, Union, ClassVar


def read_modl(path: str) -> ModlData: ...


class ModlData:
    major_version: int
    minor_version: int
    model_name: str
    skeleton_file_name: str
    material_file_names: list[str]
    animation_file_name: Optional[str]
    mesh_file_name: str
    entries: list[ModlEntryData]

    def __init__(
        self,
        major_version: int = 1,
        minor_version: int = 7,
    ) -> None: ...
    
    def save(self, path: str) -> None: ...


class ModlEntryData:
    mesh_object_name: str
    mesh_object_subindex: int
    material_label: str

    def __init__(
        self,
        mesh_object_name: str,
        mesh_object_subindex: int,
        material_label: str
    ) -> None: ...
