from ... import ssbh_data_py
from typing import NamedTuple

ParamId = ssbh_data_py.matl_data.ParamId
param_id_to_ui_name = {
    ParamId.Texture0.value: "Texture0 (COL Map Layer 1)",
    ParamId.Texture1.value: "Texture1 (COL Map Layer 2)",
    ParamId.Texture2.value: "Texture2 (Irradiance Cube Map)",
    ParamId.Texture3.value: "Texture3 (Ambient Occlusion Map)",
    ParamId.Texture4.value: "Texture4 (NOR Map)",
    ParamId.Texture5.value: "Texture5 (Emissive Map Layer 1)",
    ParamId.Texture6.value: "Texture6 (PRM Map)",
    ParamId.Texture7.value: "Texture7 (Specular Cube Map)",
    ParamId.Texture8.value: "Texture8 (Diffuse Cube Map)",
    ParamId.Texture9.value: "Texture9 (Baked Lighting Map)",
    ParamId.Texture10.value: "Texture10 (Diffuse Map Layer 1)",
    ParamId.Texture11.value: "Texture11 (Diffuse Map Layer 2)",
    ParamId.Texture12.value: "Texture12 (Diffuse Map Layer 3)",
    ParamId.Texture13.value: "Texture13 (Projection Light Map)",
    ParamId.Texture14.value: "Texture14 (Emissive Map Layer 2)",
    ParamId.Texture15.value: "Texture15 (Unused)",
    ParamId.Texture16.value: "Texture16 (Ink Normal Map)",
    ParamId.Texture17.value: "Texture17 (Unused)",
    ParamId.Texture18.value: "Texture18 (Unused)",
    ParamId.Texture19.value: "Texture19 (Unused)",
    ParamId.Sampler0.value: "Sampler0 (COL Map Layer 1)",
    ParamId.Sampler1.value: "Sampler1 (COL Map Layer 2)",
    ParamId.Sampler2.value: "Sampler2 (Irradiance Cube Map)",
    ParamId.Sampler3.value: "Sampler3 (Ambient Occlusion Map)",
    ParamId.Sampler4.value: "Sampler4 (NOR Map)",
    ParamId.Sampler5.value: "Sampler5 (Emissive Map Layer 1)",
    ParamId.Sampler6.value: "Sampler6 (PRM Map)",
    ParamId.Sampler7.value: "Sampler7 (Specular Cube Map)",
    ParamId.Sampler8.value: "Sampler8 (Diffuse Cube Map)",
    ParamId.Sampler9.value: "Sampler9 (Baked Lighting Map)",
    ParamId.Sampler10.value: "Sampler10 (Diffuse Map Layer 1)",
    ParamId.Sampler11.value: "Sampler11 (Diffuse Map Layer 2)",
    ParamId.Sampler12.value: "Sampler12 (Diffuse Map Layer 3)",
    ParamId.Sampler13.value: "Sampler13 (Projection Light Map)",
    ParamId.Sampler14.value: "Sampler14 (Emissive Map Layer 2)",
    ParamId.Sampler15.value: "Sampler15 (Unused)",
    ParamId.Sampler16.value: "Sampler16 (Ink Normal Map)",
    ParamId.Sampler17.value: "Sampler17 (Unused)",
    ParamId.Sampler18.value: "Sampler18 (Unused)",
    ParamId.Sampler19.value: "Sampler19 (Unused)", 
    ParamId.CustomVector0.value: "CV 0 (Minimum Texture Alpha)",
    ParamId.CustomVector1.value: "CV 1",
    ParamId.CustomVector2.value: "CV 2",
    ParamId.CustomVector3.value: "CV 3 (Emission Color Multipler)",
    ParamId.CustomVector4.value: "CV 4",
    ParamId.CustomVector5.value: "CV 5",
    ParamId.CustomVector6.value: "CV 6 (UV Transform Layer 1)",
    ParamId.CustomVector7.value: "CV 7",
    ParamId.CustomVector8.value: "CV 8 (Final Color Multiplier)",
    ParamId.CustomVector9.value: "CV 9",
    ParamId.CustomVector10.value: "CV 10",
    ParamId.CustomVector11.value: "CV 11 (Fake SSS Color)",
    ParamId.CustomVector12.value: "CV 12",
    ParamId.CustomVector13.value: "CV 13 (Diffuse Color Multiplier)",
    ParamId.CustomVector14.value: "CV 14 (Rim Light RGB + Intensity)",
    ParamId.CustomVector15.value: "CV 15",
    ParamId.CustomVector16.value: "CV 16",
    ParamId.CustomVector17.value: "CV 17",
    ParamId.CustomVector18.value: "CV 18 (Sprite Sheet Params)",
    ParamId.CustomVector19.value: "CV 19",
    ParamId.CustomVector20.value: "CV 20",
    ParamId.CustomVector21.value: "CV 21",
    ParamId.CustomVector22.value: "CV 22",
    ParamId.CustomVector23.value: "CV 23",
    ParamId.CustomVector24.value: "CV 24",
    ParamId.CustomVector25.value: "CV 25",
    ParamId.CustomVector26.value: "CV 26",
    ParamId.CustomVector27.value: "CV 27",
    ParamId.CustomVector28.value: "CV 28",
    ParamId.CustomVector29.value: "CV 29",
    ParamId.CustomVector30.value: "CV 30 (Fake SSS Params)",
    ParamId.CustomVector31.value: "CV 31 (UV Transform Layer 2)",
    ParamId.CustomVector32.value: "CV 32 (UV Transform Layer 3)",
    ParamId.CustomVector33.value: "CV 33",
    ParamId.CustomVector34.value: "CV 34",
    ParamId.CustomVector35.value: "CV 35",
    ParamId.CustomVector36.value: "CV 36",
    ParamId.CustomVector37.value: "CV 37",
    ParamId.CustomVector38.value: "CV 38",
    ParamId.CustomVector39.value: "CV 39",
    ParamId.CustomVector40.value: "CV 40",
    ParamId.CustomVector41.value: "CV 41",
    ParamId.CustomVector42.value: "CV 42",
    ParamId.CustomVector43.value: "CV 43",
    ParamId.CustomVector44.value: "CV 44",
    ParamId.CustomVector45.value: "CV 45",
    ParamId.CustomVector46.value: "CV 46 (Bayonetta Anim Hair/Skin Blend)",
    ParamId.CustomVector47.value: "CV 47 (Mesh-wide PRM)",
    ParamId.CustomFloat0.value: "CF 0 (Texture3 Additional Intensity)",
    ParamId.CustomFloat1.value: "CF 1",
    ParamId.CustomFloat2.value: "CF 2",
    ParamId.CustomFloat3.value: "CF 3",
    ParamId.CustomFloat4.value: "CF 4 (UV Distortion Intensity)",
    ParamId.CustomFloat5.value: "CF 5",
    ParamId.CustomFloat6.value: "CF 6",
    ParamId.CustomFloat7.value: "CF 7",
    ParamId.CustomFloat8.value: "CF 8 (Albedo Color Tint Intensity)",
    ParamId.CustomFloat9.value: "CF 9",
    ParamId.CustomFloat10.value: "CF 10 (Specular Anisotropy)",
    ParamId.CustomFloat11.value: "CF 11",
    ParamId.CustomFloat12.value: "CF 12",
    ParamId.CustomFloat13.value: "CF 13",
    ParamId.CustomFloat14.value: "CF 14",
    ParamId.CustomFloat15.value: "CF 15",
    ParamId.CustomFloat16.value: "CF 16 (Vertex Shader Z Offset)",
    ParamId.CustomFloat17.value: "CF 17",
    ParamId.CustomFloat18.value: "CF 18",
    ParamId.CustomFloat19.value: "CF 19",
    ParamId.CustomBoolean0.value: "CB 0",
    ParamId.CustomBoolean1.value: "CB 1 (PRM Specular Override)",
    ParamId.CustomBoolean2.value: "CB 2 (Alpha Override)",
    ParamId.CustomBoolean3.value: "CB 3 (Enable Specular light)",
    ParamId.CustomBoolean4.value: "CB 4 (Enable Specular Cubemap)",
    ParamId.CustomBoolean5.value: "CB 5 (Enable CV 6 (UV Transform Layer 1))",
    ParamId.CustomBoolean6.value: "CB 6 (Enable CV 31 (UV Transform Layer 2))",
    ParamId.CustomBoolean7.value: "CB 7 (Enable CV 32 (UV Transform Layer 3))",
    ParamId.CustomBoolean8.value: "CB 8 ",
    ParamId.CustomBoolean9.value: "CB 9 (Enable CV 18 Z (Manual Spritesheet Selection))",
    ParamId.CustomBoolean10.value: "CB 10 ",
    ParamId.CustomBoolean11.value: "CB 11 (Enable additive texture blender)",
    ParamId.CustomBoolean12.value: "CB 12",
    ParamId.CustomBoolean13.value: "CB 13",
    ParamId.CustomBoolean14.value: "CB 14",
    ParamId.CustomBoolean15.value: "CB 15",
    ParamId.CustomBoolean16.value: "CB 16",
    ParamId.CustomBoolean17.value: "CB 17",
    ParamId.CustomBoolean18.value: "CB 18",
    ParamId.CustomBoolean19.value: "CB 19",
    ParamId.BlendState0.value: "Blend State 0",
    ParamId.BlendState1.value: "Blend State 1?",
    ParamId.BlendState2.value: "Blend State 2?",
    ParamId.BlendState3.value: "Blend State 3?",
    ParamId.BlendState4.value: "Blend State 4?",
    ParamId.BlendState5.value: "Blend State 5?",
    ParamId.BlendState6.value: "Blend State 6?",
    ParamId.BlendState7.value: "Blend State 7?",
    ParamId.BlendState8.value: "Blend State 8?",
    ParamId.BlendState9.value: "Blend State 9?",
    ParamId.BlendState10.value: "Blend State 10?",
    ParamId.RasterizerState0.value: "Rasterizer State 0",
    ParamId.RasterizerState1.value: "Rasterizer State 1?",
    ParamId.RasterizerState2.value: "Rasterizer State 2?",
    ParamId.RasterizerState3.value: "Rasterizer State 3?",
    ParamId.RasterizerState4.value: "Rasterizer State 4?",
    ParamId.RasterizerState5.value: "Rasterizer State 5?",
    ParamId.RasterizerState6.value: "Rasterizer State 6?",
    ParamId.RasterizerState7.value: "Rasterizer State 7?",
    ParamId.RasterizerState8.value: "Rasterizer State 8?",
    ParamId.RasterizerState9.value: "Rasterizer State 9?",
    ParamId.RasterizerState10.value: "Rasterizer State 10?",
}

class Vec4SocketParams(NamedTuple):
    x_socket_name: str
    y_socket_name: str
    z_socket_name: str
    w_socket_name: str
    default_value: tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0)

vec4_param_name_to_socket_params: dict[str, Vec4SocketParams] = {
    ParamId.CustomVector0.name: Vec4SocketParams(
        "CV 0 X (Min Texture Alpha)",
        "CV 0 Y",
        "CV 0 Z",
        "CV 0 W",
    ),
    ParamId.CustomVector1.name: Vec4SocketParams(
        "CV 1 X",
        "CV 1 Y",
        "CV 1 Z",
        "CV 1 W",
    ),
    ParamId.CustomVector2.name: Vec4SocketParams(
        "CV 2 X",
        "CV 2 Y",
        "CV 2 Z",
        "CV 2 W",
    ),
    ParamId.CustomVector3.name: Vec4SocketParams(
        "CV 3 X (Emission Scale R)",
        "CV 3 Y (Emission Scale G)",
        "CV 3 Z (Emission Scale B)",
        "CV 3 W",
        (1.0, 1.0, 1.0, 1.0),
    ),
    ParamId.CustomVector4.name: Vec4SocketParams(
        "CV 4 X",
        "CV 4 Y",
        "CV 4 Z",
        "CV 4 W",
    ),
    ParamId.CustomVector5.name: Vec4SocketParams(
        "CV 5 X",
        "CV 5 Y",
        "CV 5 Z",
        "CV 5 W",
    ),
    ParamId.CustomVector6.name: Vec4SocketParams(
        "CV 6 X (UV Layer 1 Scale X)",
        "CV 6 Y (UV Layer 1 Scale Y)",
        "CV 6 Z (UV Layer 1 Trans X)",
        "CV 6 W (UV Layer 1 Trans Y)",
    ),
    ParamId.CustomVector7.name: Vec4SocketParams(
        "CV 7 X",
        "CV 7 Y",
        "CV 7 Z",
        "CV 7 W",
    ),
    ParamId.CustomVector8.name: Vec4SocketParams(
        "CV 8 X (Final Color Scale R)",
        "CV 8 Y (Final Color Scale G)",
        "CV 8 Z (Final Color Scale B)",
        "CV 8 W",
    ),
    ParamId.CustomVector9.name: Vec4SocketParams(
        "CV 9 X",
        "CV 9 Y",
        "CV 9 Z",
        "CV 9 W",
    ),
    ParamId.CustomVector10.name: Vec4SocketParams(
        "CV 10 X",
        "CV 10 Y",
        "CV 10 Z",
        "CV 10 W",
    ),
    ParamId.CustomVector11.name:Vec4SocketParams(
        "CV 11 X (Fake SSS Color R)",
        "CV 11 Y (Fake SSS Color G)",
        "CV 11 Z (Fake SSS Color B)",
        "CV 11 W",
    ),
    ParamId.CustomVector12.name:Vec4SocketParams(
        "CV 12 X",
        "CV 12 Y",
        "CV 12 Z",
        "CV 12 W",
    ),
    ParamId.CustomVector13.name: Vec4SocketParams(
        "CV 13 X (Diffuse Color Scale R)",
        "CV 13 Y (Diffuse Color Scale G)",
        "CV 13 Z (Diffuse Color Scale B)",
        "CV 13 W",
        (1.0, 1.0, 1.0, 1.0),
    ),
    ParamId.CustomVector14.name:Vec4SocketParams(
        "CV 14 X (Rim Light Color R)",
        "CV 14 Y (Rim Light Color G)",
        "CV 14 Z (Rim Light Color B)",
        "CV 14 W (Rim Light Blend Factor)",
    ),
    ParamId.CustomVector15.name:Vec4SocketParams(
        "CV 15 X",
        "CV 15 Y",
        "CV 15 Z",
        "CV 15 W",
    ),
    ParamId.CustomVector16.name: Vec4SocketParams(
        "CV 16 X",
        "CV 16 Y",
        "CV 16 Z",
        "CV 16 W",
    ),
    ParamId.CustomVector17.name:Vec4SocketParams(
        "CV 17 X",
        "CV 17 Y",
        "CV 17 Z",
        "CV 17 W",
    ),
    ParamId.CustomVector18.name:Vec4SocketParams(
        "CV 18 X (Sprite Sheet Column Count)",
        "CV 18 Y (Sprite Sheet Row Count)",
        "CV 18 Z (Frames Per Sprite)",
        "CV 18 W (Total Sprite Count)",
    ),
    ParamId.CustomVector19.name:Vec4SocketParams(
        "CV 19 X",
        "CV 19 Y",
        "CV 19 Z",
        "CV 19 W",
    ),
    ParamId.CustomVector20.name:Vec4SocketParams(
        "CV 20 X",
        "CV 20 Y",
        "CV 20 Z",
        "CV 20 W",
    ),
    ParamId.CustomVector21.name: Vec4SocketParams(
        "CV 21 X",
        "CV 21 Y",
        "CV 21 Z",
        "CV 21 W",
    ),
    ParamId.CustomVector22.name:Vec4SocketParams(
        "CV 22 X",
        "CV 22 Y",
        "CV 22 Z",
        "CV 22 W",
    ),
    ParamId.CustomVector23.name:Vec4SocketParams(
        "CV 23 X",
        "CV 23 Y",
        "CV 23 Z",
        "CV 23 W",
    ),
    ParamId.CustomVector24.name:Vec4SocketParams(
        "CV 24 X",
        "CV 24 Y",
        "CV 24 Z",
        "CV 24 W",
    ),
    ParamId.CustomVector25.name:Vec4SocketParams(
        "CV 25 X",
        "CV 25 Y",
        "CV 25 Z",
        "CV 25 W",
    ),
    ParamId.CustomVector26.name:Vec4SocketParams(
        "CV 26 X",
        "CV 26 Y",
        "CV 26 Z",
        "CV 26 W",
    ),
    ParamId.CustomVector27.name:Vec4SocketParams(
        "CV 27 X",
        "CV 27 Y",
        "CV 27 Z",
        "CV 27 W",
    ),
    ParamId.CustomVector28.name:Vec4SocketParams(
        "CV 28 X",
        "CV 28 Y",
        "CV 28 Z",
        "CV 28 W",
    ),
    ParamId.CustomVector29.name:Vec4SocketParams(
        "CV 29 X",
        "CV 29 Y",
        "CV 29 Z",
        "CV 29 W",
    ),
    ParamId.CustomVector30.name:Vec4SocketParams(
        "CV 30 X (Fake SSS Blend Factor)",
        "CV 30 Y (Fake SSS Sharpness)",
        "CV 30 Z",
        "CV 30 W",
    ),
    ParamId.CustomVector31.name:Vec4SocketParams(
        "CV 31 X (UV Layer 2 Scale X)",
        "CV 31 Y (UV Layer 2 Scale Y)",
        "CV 31 Z (UV Layer 2 Trans X)",
        "CV 31 W (UV Layer 2 Trans Y)",
    ),
    ParamId.CustomVector32.name:Vec4SocketParams(
        "CV 32 X (UV Layer 3 Scale X)",
        "CV 32 Y (UV Layer 3 Scale Y)",
        "CV 32 Z (UV Layer 3 Trans X)",
        "CV 32 W (UV Layer 3 Trans Y)",
    ),
    ParamId.CustomVector33.name:Vec4SocketParams(
        "CV 33 X (UV Layer 4 Transform?)",
        "CV 33 Y (UV Layer 4 Transform?)",
        "CV 33 Z (UV Layer 4 Transform?)",
        "CV 33 W (UV Layer 4 Transform?)",
    ),
    ParamId.CustomVector34.name:Vec4SocketParams(
        "CV 34 X (UV Transform Dual Normal)",
        "CV 34 Y (UV Transform Dual Normal)",
        "CV 34 Z (UV Transform Dual Normal)",
        "CV 34 W (UV Transform Dual Normal)",
    ),
    ParamId.CustomVector35.name:Vec4SocketParams(
        "CV 35 X",
        "CV 35 Y",
        "CV 35 Z",
        "CV 35 W",
    ),
    ParamId.CustomVector36.name:Vec4SocketParams(
        "CV 36 X",
        "CV 36 Y",
        "CV 36 Z",
        "CV 36 W",
    ),
    ParamId.CustomVector37.name:Vec4SocketParams(
        "CV 37 X",
        "CV 37 Y",
        "CV 37 Z",
        "CV 37 W",
    ),
    ParamId.CustomVector38.name:Vec4SocketParams(
        "CV 38 X",
        "CV 38 Y",
        "CV 38 Z",
        "CV 38 W",
    ),
    ParamId.CustomVector39.name:Vec4SocketParams(
        "CV 39 X",
        "CV 39 Y",
        "CV 39 Z",
        "CV 39 W",
    ),
    ParamId.CustomVector40.name:Vec4SocketParams(
        "CV 40 X",
        "CV 40 Y",
        "CV 40 Z",
        "CV 40 W",
    ),
    ParamId.CustomVector41.name:Vec4SocketParams(
        "CV 41 X",
        "CV 41 Y",
        "CV 41 Z",
        "CV 41 W",
    ),
    ParamId.CustomVector42.name:Vec4SocketParams(
        "CV 42 X",
        "CV 42 Y",
        "CV 42 Z",
        "CV 42 W",
    ),
    ParamId.CustomVector43.name:Vec4SocketParams(
        "CV 43 X",
        "CV 43 Y",
        "CV 43 Z",
        "CV 43 W",
    ),
    ParamId.CustomVector44.name:Vec4SocketParams(
        "CV 44 X",
        "CV 44 Y",
        "CV 44 Z",
        "CV 44 W",
    ),
    ParamId.CustomVector45.name:Vec4SocketParams(
        "CV 45 X",
        "CV 45 Y",
        "CV 45 Z",
        "CV 45 W",
    ),
    ParamId.CustomVector46.name:Vec4SocketParams(
        "CV 46 X (Bayo Anim Skin R)",
        "CV 46 Y (Bayo Anim Skin G)",
        "CV 46 Z (Bayo Anim Skin B)",
        "CV 46 W (Bayo Anim Alpha)",
    ),
    ParamId.CustomVector47.name:Vec4SocketParams(
        "CV 47 X (PRM R Metalness)",
        "CV 47 Y (PRM G Roughness)",
        "CV 47 Z (PRM B AO)",
        "CV 47 W (PRM A Specular Boost)",
    ),
}

# Texture Params end up with two sockets each, one for the RGB and the other for the Alpha
class SplitTextureSocketParams(NamedTuple):
    rgb_socket_name: str
    alpha_socket_name: str
    default_rgba: tuple[float,float,float,float] = (0.0, 0.0, 0.0, 1.0)

texture_param_name_to_socket_params: dict[str, SplitTextureSocketParams]= {
    ParamId.Texture0.name: SplitTextureSocketParams(
        'Texture0 RGB (Col Map Layer 1)',
        'Texture0 Alpha (Col Map Layer 1)',
    ),
    ParamId.Texture1.name: SplitTextureSocketParams(
        'Texture1 RGB (Col Map Layer 2)',
        'Texture1 Alpha (Col Map Layer 2)',
        (0.0, 0.0, 0.0, 0.0)
    ),
    ParamId.Texture2.name: SplitTextureSocketParams(
        'Texture2 RGB (Irradiance Cube Map)',
        'Texture2 Alpha (Irradiance Cube Map)',
    ),
    ParamId.Texture3.name: SplitTextureSocketParams(
        'Texture3 RGB (Ambient Occlusion Map)',
        'Texture3 Alpha (Ambient Occlusion Map)',
    ),
    ParamId.Texture4.name: SplitTextureSocketParams(
        'Texture4 RGB (NOR Map)',
        'Texture4 Alpha (NOR Map Cavity Channel)',
        (0.5, 0.5, 0.0, 1.0),
    ),
    ParamId.Texture5.name: SplitTextureSocketParams(
        'Texture5 RGB (Emissive Map Layer 1)',
        'Texture5 Alpha (Emissive Map Layer 1)',
    ),
    ParamId.Texture6.name: SplitTextureSocketParams(
        'Texture6 RGB (PRM Map)',
        'Texture6 Alpha (PRM Map Specular)',
        (0.0, 1.0, 1.0, 0.0),
    ),
    ParamId.Texture7.name: SplitTextureSocketParams(
        'Texture7 RGB (Specular Cube Map)',
        'Texture7 Alpha (Specular Cube Map)',
    ),
    ParamId.Texture8.name: SplitTextureSocketParams(
        'Texture8 RGB (Diffuse Cube Map)',
        'Texture8 Alpha (Diffuse Cube Map)',
    ),
    ParamId.Texture9.name: SplitTextureSocketParams(
        'Texture9 RGB (Baked Lighting Map)',
        'Texture9 Alpha (Baked Lighting Map)',
    ),
    ParamId.Texture10.name: SplitTextureSocketParams(
        'Texture10 RGB (Diffuse Map Layer 1)',
        'Texture10 Alpha (Diffuse Map Layer 1)',
    ),
    ParamId.Texture11.name: SplitTextureSocketParams(
        'Texture11 RGB (Diffuse Map Layer 2)',
        'Texture11 Alpha (Diffuse Map Layer 2)',
    ),
    ParamId.Texture12.name: SplitTextureSocketParams(
        'Texture12 RGB (Diffuse Map Layer 3)',
        'Texture12 Alpha (Diffuse Map Layer 3)',
    ),
    ParamId.Texture13.name: SplitTextureSocketParams(
        'Texture13 RGB (Projection Light Map)',
        'Texture13 Alpha (Projection Light Map)',
    ),
    ParamId.Texture14.name: SplitTextureSocketParams(
        'Texture14 RGB (Emissive Map Layer 2)',
        'Texture14 Alpha (Emissive Map Layer 2)',
        (0.0, 0.0, 0.0, 0.0)
    ),
    ParamId.Texture15.name: SplitTextureSocketParams(
        'Texture15 RGB (Unused)',
        'Texture15 Alpha (Unused)',
    ),
    ParamId.Texture16.name: SplitTextureSocketParams(
        'Texture16 RGB (Ink Normal Map)',
        'Texture16 Alpha (Ink Normal Map)',
    ),
    ParamId.Texture17.name: SplitTextureSocketParams(
        'Texture17 RGB (Unused)',
        'Texture17 Alpha (Unused)',
    ),
    ParamId.Texture18.name: SplitTextureSocketParams(
        'Texture18 RGB (Unused)',
        'Texture18 Alpha (Unused)',
    ),
    ParamId.Texture19.name: SplitTextureSocketParams(
        'Texture19 RGB (Unused)',
        'Texture19 RGB (Unused)',
    ),
}

vector_param_id_values: set[int] = {
    ParamId.CustomVector0.value,
    ParamId.CustomVector1.value,
    ParamId.CustomVector2.value,
    ParamId.CustomVector3.value,
    ParamId.CustomVector4.value,
    ParamId.CustomVector5.value,
    ParamId.CustomVector6.value,
    ParamId.CustomVector7.value,
    ParamId.CustomVector8.value,
    ParamId.CustomVector9.value,
    ParamId.CustomVector10.value,
    ParamId.CustomVector11.value,
    ParamId.CustomVector12.value,
    ParamId.CustomVector13.value,
    ParamId.CustomVector14.value,
    ParamId.CustomVector15.value,
    ParamId.CustomVector16.value,
    ParamId.CustomVector17.value,
    ParamId.CustomVector18.value,
    ParamId.CustomVector19.value,
    ParamId.CustomVector20.value,
    ParamId.CustomVector21.value,
    ParamId.CustomVector22.value,
    ParamId.CustomVector23.value,
    ParamId.CustomVector24.value,
    ParamId.CustomVector25.value,
    ParamId.CustomVector26.value,
    ParamId.CustomVector27.value,
    ParamId.CustomVector28.value,
    ParamId.CustomVector29.value,
    ParamId.CustomVector30.value,
    ParamId.CustomVector31.value,
    ParamId.CustomVector32.value,
    ParamId.CustomVector33.value,
    ParamId.CustomVector34.value,
    ParamId.CustomVector35.value,
    ParamId.CustomVector36.value,
    ParamId.CustomVector37.value,
    ParamId.CustomVector38.value,
    ParamId.CustomVector39.value,
    ParamId.CustomVector40.value,
    ParamId.CustomVector41.value,
    ParamId.CustomVector42.value,
    ParamId.CustomVector43.value,
    ParamId.CustomVector44.value,
    ParamId.CustomVector45.value,
    ParamId.CustomVector46.value,
    ParamId.CustomVector47.value,
}

vector_param_id_value_to_default_value: dict[int, tuple[float,float,float,float]] = {
    ParamId.CustomVector0.value: (0,0,0,0),
    ParamId.CustomVector1.value: (1,1,1,1),
    ParamId.CustomVector2.value: (1,1,1,1),
    ParamId.CustomVector3.value: (1,1,1,1),
    ParamId.CustomVector4.value: (1,1,1,1),
    ParamId.CustomVector5.value: (1,1,1,1),
    ParamId.CustomVector6.value: (1,1,0,0),
    ParamId.CustomVector7.value: (1,1,1,1),
    ParamId.CustomVector8.value: (1,1,1,1),
    ParamId.CustomVector9.value: (1,1,1,1),
    ParamId.CustomVector10.value: (1,1,1,1),
    ParamId.CustomVector11.value: (0,0,0,1),
    ParamId.CustomVector12.value: (1,1,1,1),
    ParamId.CustomVector13.value: (1,1,1,1),
    ParamId.CustomVector14.value: (1,1,1,1),
    ParamId.CustomVector15.value: (1,1,1,1),
    ParamId.CustomVector16.value: (1,1,1,1),
    ParamId.CustomVector17.value: (1,1,1,1),
    ParamId.CustomVector18.value: (1,1,1,1),
    ParamId.CustomVector19.value: (1,1,1,1),
    ParamId.CustomVector20.value: (1,1,1,1),
    ParamId.CustomVector21.value: (1,1,1,1),
    ParamId.CustomVector22.value: (1,1,1,1),
    ParamId.CustomVector23.value: (1,1,1,1),
    ParamId.CustomVector24.value: (1,1,1,1),
    ParamId.CustomVector25.value: (1,1,1,1),
    ParamId.CustomVector26.value: (1,1,1,1),
    ParamId.CustomVector27.value: (1,1,1,1),
    ParamId.CustomVector28.value: (1,1,1,1),
    ParamId.CustomVector29.value: (1,1,1,1),
    ParamId.CustomVector30.value: (0,0,0,1),
    ParamId.CustomVector31.value: (1,1,0,0),
    ParamId.CustomVector32.value: (1,1,0,0),
    ParamId.CustomVector33.value: (1,1,1,1),
    ParamId.CustomVector34.value: (1,1,0,0),
    ParamId.CustomVector35.value: (1,1,1,1),
    ParamId.CustomVector36.value: (1,1,1,1),
    ParamId.CustomVector37.value: (1,1,1,1),
    ParamId.CustomVector38.value: (1,1,1,1),
    ParamId.CustomVector39.value: (1,1,1,1),
    ParamId.CustomVector40.value: (1,1,1,1),
    ParamId.CustomVector41.value: (1,1,1,1),
    ParamId.CustomVector42.value: (1,1,1,1),
    ParamId.CustomVector43.value: (1,1,1,1),
    ParamId.CustomVector44.value: (1,1,1,1),
    ParamId.CustomVector45.value: (1,1,1,1),
    ParamId.CustomVector46.value: (1,1,1,1),
    ParamId.CustomVector47.value: (1,1,1,1),
}

texture_param_id_values = {
    ParamId.Texture0.value,
    ParamId.Texture1.value,
    ParamId.Texture2.value,
    ParamId.Texture3.value,
    ParamId.Texture4.value,
    ParamId.Texture5.value,
    ParamId.Texture6.value,
    ParamId.Texture7.value,
    ParamId.Texture8.value,
    ParamId.Texture9.value,
    ParamId.Texture10.value,
    ParamId.Texture11.value,
    ParamId.Texture12.value,
    ParamId.Texture13.value,
    ParamId.Texture14.value,
    ParamId.Texture15.value,
    ParamId.Texture16.value,
    ParamId.Texture17.value,
    ParamId.Texture18.value,
    ParamId.Texture19.value,
}

sampler_param_id_values = {
    ParamId.Sampler0.value, 
    ParamId.Sampler1.value, 
    ParamId.Sampler2.value, 
    ParamId.Sampler3.value, 
    ParamId.Sampler4.value, 
    ParamId.Sampler5.value, 
    ParamId.Sampler6.value, 
    ParamId.Sampler7.value, 
    ParamId.Sampler8.value, 
    ParamId.Sampler9.value, 
    ParamId.Sampler10.value,
    ParamId.Sampler11.value,
    ParamId.Sampler12.value,
    ParamId.Sampler13.value,
    ParamId.Sampler14.value,
    ParamId.Sampler15.value,
    ParamId.Sampler16.value,
    ParamId.Sampler17.value,
    ParamId.Sampler18.value,
    ParamId.Sampler19.value,
}

float_param_id_values = {
    ParamId.CustomFloat0.value,
    ParamId.CustomFloat1.value,
    ParamId.CustomFloat2.value,
    ParamId.CustomFloat3.value,
    ParamId.CustomFloat4.value,
    ParamId.CustomFloat5.value,
    ParamId.CustomFloat6.value,
    ParamId.CustomFloat7.value,
    ParamId.CustomFloat8.value,
    ParamId.CustomFloat9.value,
    ParamId.CustomFloat10.value,
    ParamId.CustomFloat11.value,
    ParamId.CustomFloat12.value,
    ParamId.CustomFloat13.value,
    ParamId.CustomFloat14.value,
    ParamId.CustomFloat15.value,
    ParamId.CustomFloat16.value,
    ParamId.CustomFloat17.value,
    ParamId.CustomFloat18.value,
    ParamId.CustomFloat19.value,
}

float_param_id_value_to_default_value = {
    ParamId.CustomFloat0.value: 0.0,
    ParamId.CustomFloat1.value:  0.0,
    ParamId.CustomFloat2.value:  0.0,
    ParamId.CustomFloat3.value:  0.0,
    ParamId.CustomFloat4.value:  0.0,
    ParamId.CustomFloat5.value:  0.0,
    ParamId.CustomFloat6.value:  0.0,
    ParamId.CustomFloat7.value:  0.0,
    ParamId.CustomFloat8.value:  0.0,
    ParamId.CustomFloat9.value:  0.0,
    ParamId.CustomFloat10.value:  0.0,
    ParamId.CustomFloat11.value:  0.0,
    ParamId.CustomFloat12.value:  0.0,
    ParamId.CustomFloat13.value:  0.0,
    ParamId.CustomFloat14.value:  0.0,
    ParamId.CustomFloat15.value:  0.0,
    ParamId.CustomFloat16.value:  0.0,
    ParamId.CustomFloat17.value:  0.0,
    ParamId.CustomFloat18.value:  0.0,
    ParamId.CustomFloat19.value:  0.0,
} 

bool_param_id_values = {
    ParamId.CustomBoolean0.value,
    ParamId.CustomBoolean1.value,
    ParamId.CustomBoolean2.value,
    ParamId.CustomBoolean3.value,
    ParamId.CustomBoolean4.value,
    ParamId.CustomBoolean5.value,
    ParamId.CustomBoolean6.value,
    ParamId.CustomBoolean7.value,
    ParamId.CustomBoolean8.value,
    ParamId.CustomBoolean9.value,
    ParamId.CustomBoolean10.value,
    ParamId.CustomBoolean11.value,
    ParamId.CustomBoolean12.value,
    ParamId.CustomBoolean13.value,
    ParamId.CustomBoolean14.value,
    ParamId.CustomBoolean15.value,
    ParamId.CustomBoolean16.value,
    ParamId.CustomBoolean17.value,
    ParamId.CustomBoolean18.value,
    ParamId.CustomBoolean19.value,
}

bool_param_id_value_to_default_value = {
    ParamId.CustomBoolean0.value: True,
    ParamId.CustomBoolean1.value: True,
    ParamId.CustomBoolean2.value: False,
    ParamId.CustomBoolean3.value: True,
    ParamId.CustomBoolean4.value: True,
    ParamId.CustomBoolean5.value: True,
    ParamId.CustomBoolean6.value: True,
    ParamId.CustomBoolean7.value: True,
    ParamId.CustomBoolean8.value: True,
    ParamId.CustomBoolean9.value: True,
    ParamId.CustomBoolean10.value: True,
    ParamId.CustomBoolean11.value: False,
    ParamId.CustomBoolean12.value: False,
    ParamId.CustomBoolean13.value: True,
    ParamId.CustomBoolean14.value: True,
    ParamId.CustomBoolean15.value: True,
    ParamId.CustomBoolean16.value: True,
    ParamId.CustomBoolean17.value: True,
    ParamId.CustomBoolean18.value: True,
    ParamId.CustomBoolean19.value: True,
}



blend_state_param_id_values = {
    ParamId.BlendState0.value, 
    ParamId.BlendState1.value, 
    ParamId.BlendState2.value, 
    ParamId.BlendState3.value, 
    ParamId.BlendState4.value, 
    ParamId.BlendState5.value, 
    ParamId.BlendState6.value, 
    ParamId.BlendState7.value, 
    ParamId.BlendState8.value, 
    ParamId.BlendState9.value, 
    ParamId.BlendState10.value,
}

rasterizer_state_param_id_values = {
    ParamId.RasterizerState0.value,
    ParamId.RasterizerState1.value,
    ParamId.RasterizerState2.value,
    ParamId.RasterizerState3.value,
    ParamId.RasterizerState4.value,
    ParamId.RasterizerState5.value,
    ParamId.RasterizerState6.value,
    ParamId.RasterizerState7.value,
    ParamId.RasterizerState8.value,
    ParamId.RasterizerState9.value,
    ParamId.RasterizerState10.value,
}